/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": process.env.REACT_APP_AWS_PROJECT_REGION || '',
  "aws_appsync_graphqlEndpoint": process.env.REACT_APP_AWS_APPSYNC_GRAPHQL_ENDPOINT || '',
  "aws_appsync_region": process.env.REACT_APP_AWS_APPSYNC_REGION || '',
  "aws_appsync_authenticationType": process.env.REACT_APP_AWS_APPSYNC_AUTHENTICATION_TYPE || '',
  "aws_appsync_apiKey": process.env.REACT_APP_AWS_APPSYNC_API_KEY || '',
  "aws_cognito_identity_pool_id": process.env.REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID || '',
  "aws_cognito_region": process.env.REACT_APP_AWS_COGNITO_REGION || '',
  "aws_user_pools_id": process.env.REACT_APP_AWS_USER_POOLS_ID || '',
  "aws_user_pools_web_client_id": process.env.REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID || '',
  "oauth": JSON.parse(process.env.REACT_APP_OAUTH) || {},
  "federationTarget": process.env.REACT_APP_FEDERATION_TARGET || ''
};


export default awsmobile;
